services:
  matemat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_MATEMAT_3000
      - GENERATOR_URL=http://og-image-generator:3003/og-image.png
      - GENERATOR_USER=matemat
      - GENERATOR_PASS=$SERVICE_PASSWORD_GENERATOR
      - INTERNAL_BASE_URL=http://matemat:3000
      - DATABASE_PATH=/data/matemat.db
      - UPLOADS_DIR=/data/uploads
    volumes:
      - matemat-data:/data
    depends_on:
      - og-image-generator

  og-image-generator:
    build:
      context: ./og-image-generator
      dockerfile: Dockerfile
    environment:
      - AUTH_USERS=matemat
      - AUTH_USER_matemat_PASSWORD=$SERVICE_PASSWORD_GENERATOR

volumes:
  matemat-data:
